spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    jpa.repositories.enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sales_system
    username: postgres
    password: s4l3s#
server:
  port: 6561
