spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    jpa:
      repositories:
        enabled: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sales_system
    username: postgres
    password: '*M4r10,kuhero1102!.'
server:
  port: 6561
